<?php

namespace Palpalasi\AdvancedMultifunctionFacade;

use Illuminate\Support\ServiceProvider;
use Palpalasi\AdvancedMultifunctionFacade\Commands\MakeAdvancedMultiFunctionFacade;

class AdvancedMultifunctionFacadeServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        if ($this->app->runningInConsole()) {
            $this->publishes([
                __DIR__ . '/../config/advanced-multifunction-facade.php' => config_path('advanced-multifunction-facade.php'),
            ], 'advanced-multifunction-facade');
        }

        if ($this->app->runningInConsole()) {
            $this->commands([
                MakeAdvancedMultiFunctionFacade::class,
            ]);
        }

    }
}
